#!/usr/bin/env bash
#
# gtk-backup installer for CachyOS / Arch-based systems.
#
#   git clone https://github.com/rjeffmyers/gtk-backup
#   cd gtk-backup
#   ./install.sh
#
# Installs missing dependencies, wires up a launcher + KDE menu entry, and
# installs the systemd --user timer. Runs the app straight from this clone,
# so keep the checkout where it is after installing.
#
# Flags:
#   --no-deps        skip the pacman dependency step
#   --no-timer       install units but don't enable the daily timer
#   --enable-linger  also run backups while logged out (loginctl enable-linger)
#   -h, --help       show this help

set -euo pipefail

# --- pretty output ---------------------------------------------------------
if [[ -t 1 ]]; then
    BOLD=$'\e[1m'; GREEN=$'\e[32m'; YELLOW=$'\e[33m'; RED=$'\e[31m'; RESET=$'\e[0m'
else
    BOLD=""; GREEN=""; YELLOW=""; RED=""; RESET=""
fi
info() { printf '%s==>%s %s\n' "$BOLD$GREEN" "$RESET" "$*"; }
warn() { printf '%s==>%s %s\n' "$BOLD$YELLOW" "$RESET" "$*"; }
die()  { printf '%s==> error:%s %s\n' "$BOLD$RED" "$RESET" "$*" >&2; exit 1; }

# --- args ------------------------------------------------------------------
DO_DEPS=1; DO_TIMER=1; DO_LINGER=0
for arg in "$@"; do
    case "$arg" in
        --no-deps)       DO_DEPS=0 ;;
        --no-timer)      DO_TIMER=0 ;;
        --enable-linger) DO_LINGER=1 ;;
        -h|--help)       sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)               die "unknown option: $arg (try --help)" ;;
    esac
done

[[ $EUID -eq 0 ]] && die "run this as your normal user, not root (it uses sudo only for pacman)."

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -d "$REPO/gtkbackup" ]] || die "can't find the gtkbackup/ package next to install.sh."

BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
UNIT_DIR="$HOME/.config/systemd/user"
LAUNCHER="$BIN_DIR/gtk-backup"

# --- 1. dependencies -------------------------------------------------------
# rsync: the engine. python + python-gobject/gtk4/libadwaita: the GUI.
# udisks2: safe-remove (udisksctl). desktop-file-utils: menu registration.
DEPS=(rsync python python-gobject gtk4 libadwaita udisks2 desktop-file-utils)

if [[ $DO_DEPS -eq 1 ]]; then
    if command -v pacman >/dev/null 2>&1; then
        missing=()
        for pkg in "${DEPS[@]}"; do
            pacman -Qq "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
        done
        if [[ ${#missing[@]} -gt 0 ]]; then
            info "Installing missing packages: ${missing[*]}"
            sudo pacman -S --needed "${missing[@]}"
        else
            info "All dependencies already present."
        fi
    else
        warn "pacman not found — skipping dependency install. Ensure these are present: ${DEPS[*]}"
    fi
else
    info "Skipping dependency install (--no-deps)."
fi

# --- 2. launcher -----------------------------------------------------------
info "Installing launcher -> $LAUNCHER"
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# gtk-backup launcher (generated by install.sh). Runs the app from its clone.
export PYTHONPATH="$REPO\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m gtkbackup "\$@"
EOF
chmod +x "$LAUNCHER"

case ":$PATH:" in
    *":$BIN_DIR:"*) : ;;
    *) warn "$BIN_DIR is not on your PATH — add it, or launch via the menu entry." ;;
esac

# --- 3. desktop entry (KDE menu) ------------------------------------------
info "Installing menu entry -> $APPS_DIR/gtkbackup.desktop"
mkdir -p "$APPS_DIR"
sed "s|^Exec=.*|Exec=$LAUNCHER|" \
    "$REPO/gtkbackup/data/gtkbackup.desktop" > "$APPS_DIR/gtkbackup.desktop"
command -v update-desktop-database >/dev/null 2>&1 && \
    update-desktop-database "$APPS_DIR" 2>/dev/null || true
if command -v kbuildsycoca6 >/dev/null 2>&1; then
    kbuildsycoca6 >/dev/null 2>&1 || true
elif command -v kbuildsycoca5 >/dev/null 2>&1; then
    kbuildsycoca5 >/dev/null 2>&1 || true
fi

# --- 4. systemd user units -------------------------------------------------
info "Installing systemd user units -> $UNIT_DIR"
mkdir -p "$UNIT_DIR"
cp "$REPO/gtkbackup/data/systemd/gtk-backup.service" "$UNIT_DIR/"
cp "$REPO/gtkbackup/data/systemd/gtk-backup.timer"   "$UNIT_DIR/"
systemctl --user daemon-reload

if [[ $DO_TIMER -eq 1 ]]; then
    info "Enabling daily timer (02:00, catches up if missed)."
    systemctl --user enable --now gtk-backup.timer
    if [[ $DO_LINGER -eq 1 ]]; then
        info "Enabling linger so backups run while logged out."
        sudo loginctl enable-linger "$USER"
    fi
else
    info "Timer installed but not enabled (--no-timer). Enable later with:"
    echo "    systemctl --user enable --now gtk-backup.timer"
fi

# --- 5. sanity check -------------------------------------------------------
info "Verifying install..."
if python3 -c "import gi; gi.require_version('Gtk','4.0'); gi.require_version('Adw','1'); from gi.repository import Gtk, Adw" 2>/dev/null; then
    ok_gui="yes"
else
    ok_gui="NO — install python-gobject/gtk4/libadwaita"
fi
echo "    launcher : $("$LAUNCHER" --list-devices >/dev/null 2>&1 && echo working || echo 'check PATH/deps')"
echo "    GUI deps : $ok_gui"

info "Done. Launch “Home Backup” from your menu, or run: gtk-backup"
echo
echo "Detected backup targets:"
"$LAUNCHER" --list-devices 2>/dev/null | sed 's/^/    /' || true
